### ISSUE TITLE
Consider installing a pacman hook to run automatically

### ISSUE THREAD

**Issue by RX14** [t-wissmann/archlinux-update-modules#1]
Using an alpm-hook, it's possible to automatically run this kind of cleanup when a package modifies `/usr/lib/modules`, which combined with an AUR package to install the script and hook would make solving the kernel modules issue as easy as installing one AUR package and forgetting about it!

**Comment by t-wissmann** [comment]
Is it allowed to run pacman commands inside an alpm hook? If yes, one can think about this indeed! The current script has the advantage that it runs as an ordinary user and only makes the sudo call if needed. I'm a bit anxious of having a shell script running as root that automatically makes `rm -rf` calls...

And one usually runs this script after rebooting. But I think it does not harm to keep the old modules directory until the next pacman run.

**Comment by RX14** [comment]
Ah yeah, you'd probably want both an alpm hook and a oneshot unit on boot. One strategy that might be possible is to use a pretransaction hook, copy the current kernel's modules to `{,.bak}`, then in a posttransaction hook, move it back. In a oneshot unit on boot, clear out any obsolete modules.

**Comment by t-wissmann** [comment]
Hm to be honest, I still don't think it's a good idea to run `rm -rf` automatically in the background. I've added an option `--dont-ask`. So if you want to, you can create an aur package containing the alpm hook that calls this script here.

If you need further changes, feel free to ask! For the time being, I'm closing this thread.

**Comment by RX14** [comment]
Thanks, I guess i'll take the easy way out and place this script with `--dont-ask` at the end of my update bash function...
