### ISSUE TITLE
Does not work with linux-lts

### ISSUE THREAD

**Issue by ddevault** [t-wissmann/archlinux-update-modules#2]
I was able to get it working with minor edits, but I broke it for other kernels so I didn't submit a patch.

**Comment by t-wissmann** [comment]
Can you show your patch? Then I can try to incorporate it.

**Comment by t-wissmann** [comment]
The script now should work for `linux-lts`. However, I could not test this explicitly since I don't use `linux-lts` on any of my machines. Can you please try it on your setup?

**Comment by hcnelson99** [comment]
I can confirm that the script works for `linux-lts`. Thank you for this nice script :)

**Comment by t-wissmann** [comment]
Thanks for the feedback!
